### ISSUE TITLE
Add unit test for invalid tickSpacing

### ISSUE THREAD

**Issue by mikeyrf** [overlay-market/v3-staker#10]
Need a unit test for require statement in [L151-152](https://github.com/overlay-market/v3-staker/blob/main/contracts/UniswapV3Staker.sol#L151) to check reverts when `tickSpacing` returned is == 0. Would slightly change the string formatting in require statement to be similar to rest of contract as well:

```
require(tickSpacing > 0, 'UniswapV3Staker::createIncentiveWithMaxRange: !fee');
```

**Comment by bigboydiamonds** [comment]
It looks like in Uniswap/v3-core repo's UniswapV3Factory.sol, function createPool() already has a require statement on [L44](https://github.com/Uniswap/v3-core/blob/main/contracts/UniswapV3Factory.sol#L44) that reverts when tickSpacing == 0. 

Would our require statement on L152 still be necessary given the require statement above?

**Comment by mikeyrf** [comment]
Yes since we're not calling `createPool()`, but replicating what `createPool()` is trying to do in getting the tickSpacing amount.

The caller of `createIncentiveWithMaxRange()` that passes in an invalid `fee` would get a `tickSpacing == 0` from the public factory method. But this `tickSpacing` of zero would then cause an error with the modulus in L155 (see [here](https://docs.soliditylang.org/en/v0.7.6/types.html#modulo)). So in practice, nothing really bad would happen, but we should probably handle the error with a user friendly revert message.

**Comment by bigboydiamonds** [comment]
Makes sense - thank you for the explanation! 

Implemented in this PR: https://github.com/overlay-market/v3-staker/pull/11
