### ISSUE TITLE
Add unit tests for deposit with minTickRange

### ISSUE THREAD

**Issue by mikeyrf** [overlay-market/v3-staker#7]
Similar to [these added tests](https://github.com/overlay-market/v3-staker/blob/6c9af4e2bacb45ba3f35f5a8393c06566894a40b/test/unit/Stakes.spec.ts#L175), would add unit tests to `Deposit.spec.ts` for min tick range violations, just to be safe.

**Comment by bigboydiamonds** [comment]
added unit test in commit: 

https://github.com/overlay-market/v3-staker/commit/3e7ea046d537e8c7ed814ca05867dc54e81ab7f1
